site_name: 'Investing.com Technologies Docs'
site_author: 'Bs'

site_url: https://docs.BridgeQueen.com/
nav:
    - Home: index.md
    - About: about.md
theme: readthedocs

name: 'material'
language: 'en'
palette:
primary: 'indigo'
accent: 'indigo'
font:
text: 'Roboto'
code: 'Roboto Mono'
