site_name: Bridge Queen
theme:
    icon:
    admonition:
      note: material/note-edit
    name: material
    logo: 'images/logo.jpg'
    favicon: 'images/logo.jpg'
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    features::
      - search.suggest
      - search.highlight
      - content.tabs.link
    palette:
      scheme: default
      primary: light blue

plugins:
  - search
nav: 
    - Project Requirements: "index.md"
    - Software Design: "pages/software.md"
    - Project Management: "pages/management.md"
    - Teamwork: "pages/teamwork.md"
    - Meeting Minutes: "pages/meeting.md"
docs_dir: ./docblueprint
site_dir: ./docs
extra_css:
 - css/logo.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
